version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge